<a href="https://colab.research.google.com/github/mythili-97/Python-DA-Assignment-1/blob/main/Python_DA_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Objective: **The assignment focuses on performing data analysis using Numpy arrays,Pandas Series and DataFrame.

In [ ]:
#Numpy Array Operations:
import numpy as np


In [ ]:
#1D NumPy array:
temperatures_w1=[22.5,25.3,20.8,23.4,26.1,24.8,21.9]
arr=np.array(temperatures_w1)
arr


In [ ]:
#Inspection and properties:
arr.dtype
print("Data type:",arr.dtype)
arr.size
print("Number of elements:",arr.size)
arr.shape
print("Shape:",arr.shape)

Data type: float64
Number of elements: 7
Shape: (7,)


In [ ]:
#Array operations:
Fahrenheit=(arr*9/5)+32
print(Fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
np.max(arr)
print("Maximum Temp:",np.max(arr))
np.min(arr)
print("Minimum Temp:",np.min(arr))
np.mean(arr)
print("Mean Temp:",np.mean(arr))

Maximum Temp: 26.1
Minimum Temp: 20.8
Mean Temp: 23.542857142857144


In [ ]:
#array slicing and Indexing:
arr[0:3]
print("Temperature for first three days:",arr[0:3])
arr[-2:]
print("Temperature for last two days:",arr[-2:])
arr[2:5]
print("Middle Three days:",arr[2:5])


Temperature for first three days: [22.5 25.3 20.8]
Temperature for last two days: [24.8 21.9]
Middle Three days: [20.8 23.4 26.1]


In [ ]:
#2D Array:
Temperatures=[
              [22.5,25.3,20.8,23.4,26.1,24.8,21.9],
              [19.2,22.5,21.3,24.0,23.5,22.8,20.1]
]
arr_2d=np.array(Temperatures)
arr_2d

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [ ]:
#Inspecting and Slicing 2D Array:
arr_2d.shape
print("Shape:",arr_2d.shape)
arr_2d.dtype
print("Data Type:",arr_2d.dtype)
arr_2d.size
print("Size:",arr_2d.size)

arr_2d[0:5,0:5]
print("Temperature for each weekdays:",arr_2d[0:5,0:5])
arr_2d[-2:,-2:]
print("Temperature for each weekends:",arr_2d[0:5,0:5])


Shape: (2, 7)
Data Type: float64
Size: 14
Temperature for each weekdays: [[22.5 25.3 20.8 23.4 26.1]
 [19.2 22.5 21.3 24.  23.5]]
Temperature for each weekends: [[22.5 25.3 20.8 23.4 26.1]
 [19.2 22.5 21.3 24.  23.5]]


In [ ]:
#Pandas Series:
import pandas as pd


In [ ]:
marks=[95,92,89,85,80]
ser1=pd.Series(marks,index=['Rank1','Rank2','Rank3','Rank4','Rank5'],name="Marks")
ser1

,Marks
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [ ]:
#Indexing and Slicing:
ser1.iloc[0]
print("Mark of first student:",ser1.iloc[0])
ser1.loc['Rank1':'Rank3']
print("Mark of top three ranks:",ser1.loc['Rank1':'Rank3'])
ser1.iloc[2]
print("Mark of 3rd rank student:",ser1.iloc[2])
#Boolean Mask:
ser1[ser1 > 90]


Mark of first student: 95
Mark of top three ranks: Rank1    95
Rank2    92
Rank3    89
Name: Marks, dtype: int64
Mark of 3rd rank student: 89


,Marks
Rank1,95
Rank2,92


In [ ]:
#Manipulating Series:
ser1.loc["Rank1"]=100
ser1

,Marks
Rank1,100
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [ ]:
ser1.drop('Rank5',inplace=True)
print(ser1)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: Marks, dtype: int64


In [ ]:
Cgpa=ser1/10
print(Cgpa)


Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Name: Marks, dtype: float64


In [12]:
#pandas Dataframe:
Transactions={
    "Transaction ID":[101,102,103,104,105,106,107,108,109,110],
    "Product Category":['Electronics','Clothing','Electronics','Furniture','Clothing','Electronics','Furniture','Clothing','Furniture','Electronics'],
    "Region":['North','South','North','East','West','North','East','West','South','North'],
    "Amount":[200,150,300,450,200,250,300,180,350,400]
}
Transactions

{'Transaction ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
 'Product Category': ['Electronics',
  'Clothing',
  'Electronics',
  'Furniture',
  'Clothing',
  'Electronics',
  'Furniture',
  'Clothing',
  'Furniture',
  'Electronics'],
 'Region': ['North',
  'South',
  'North',
  'East',
  'West',
  'North',
  'East',
  'West',
  'South',
  'North'],
 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}

In [13]:
import pandas as pd
Transactions=pd.DataFrame(Transactions)
Transactions


,Transaction ID,Product Category,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
#Data Exploration:
Transactions.head()

,Transaction ID,Product Category,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [ ]:
Transactions.tail()

,Transaction ID,Product Category,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
Transactions.shape


(10, 4)

In [ ]:
Transactions.columns

Index(['Transaction ID', 'Product Category', 'Region', 'Amount'], dtype='object')

In [ ]:
Transactions.dtypes

,0
Transaction ID,int64
Product Category,object
Region,object
Amount,int64


In [ ]:
Transactions[['Product Category','Amount']]

,Product Category,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [ ]:
Transactions.iloc[:,1:4]


,Product Category,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [ ]:
Filtered_Rows=Transactions[
    (Transactions['Region']=='North')&(Transactions['Amount']>200)
    ]
print(Filtered_Rows)

   Transaction ID Product Category Region  Amount
2             103      Electronics  North     300
5             106      Electronics  North     250
9             110      Electronics  North     400


In [ ]:
category_counts=Transactions['Product Category'].value_counts()
print(category_counts)

Product Category
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
Transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
Transactions.groupby('Region')['Amount'].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


In [ ]:
#Manipulating Dataframe:
Transactions.iloc[1,3]=165
Transactions

,Transaction ID,Product Category,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


In [14]:
Transactions['Discount']=Transactions['Amount']/10
Transactions

,Transaction ID,Product Category,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,150,15.0
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


In [15]:
#Removing row with TransactinID 109:
Transactions.drop(8,inplace=True)
Transactions

,Transaction ID,Product Category,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,150,15.0
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [16]:
#Deleting Discount column:
Transactions.drop("Discount",axis=1,inplace=True)
Transactions

,Transaction ID,Product Category,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400
